"""add Department

Revision ID: 309af3f7a92e
Revises: e43867247649
Create Date: 2024-04-07 15:20:35.701034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '309af3f7a92e'
down_revision = 'e43867247649'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
